feat: add check migration count in pr check

diff --git a/.github/workflows/pr-check.yml b/.github/workflows/pr-check.yml
--- a/.github/workflows/pr-check.yml
+++ b/.github/workflows/pr-check.yml
@@ -15,6 +15,16 @@ jobs:
         with:
           dotnet-version: 10.0.x
 
+      - name: Check Migration Count
+        shell: bash
+        run: |
+          git fetch origin ${{ github.base_ref }} --depth=1
+          NEW_MIGRATIONS=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep 'Migrations/' | grep '\.cs$' | grep -v '\.Designer\.cs' | grep -v 'ModelSnapshot\.cs' | wc -l)
+          if [ "$NEW_MIGRATIONS" -gt 1 ]; then
+            echo "Error: Only 1 migration per PR is allowed. You have $NEW_MIGRATIONS."
+            exit 1
+          fi
+
       - name: Restore dependencies
         run: dotnet restore
 
